# docker-compose.yml

version: "3.8"
services:
    postgres:
        image: postgres:13.5
        restart: always
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - postgres-nw-golden-racket:/var/lib/postgresql/data
        ports:
            - "5432:5432"

volumes:
    postgres-nw-golden-racket:
